<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Ashwin Nanjappa">
  <title>Code Yarns – Standard exceptions in C++</title>
  <style type="text/css">code{white-space: pre;}</style>
  <link rel="stylesheet" href="../styles.css">
  <!-- RSS feed -->
  <link rel="alternate" type="application/rss+xml" href="https://codeyarns.github.io/tech/rss.xml" />
  <!-- Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143311697-1">
  </script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-143311697-1');
  </script>
  <!-- Google Site Search -->
  <script async src="https://cse.google.com/cse.js?cx=003521915278168649297:cryrlg7hahe">
  </script>
</head>
<body>
<table style="width: 100%;">
    <tr>
        <td>
            <a href=".." class="header">Code Yarns &#128187;</a>
        </td>
        <td>
            <div class="gcse-search"></div>
        </td>
    </tr>
</table>
<hr />
<header>
<h1 class="title">Standard exceptions in C++</h1>
<p class="date">(First posted on: 2014-10-09 14:56:44+00:00)</p>
</header>
<p>All the standard exceptions in C++ are derived from the <code>exception</code> class that is defined in the <code>exception</code> header file. The standard exceptions are defined in the <code>stdexcept</code> header file.</p>
<p>The hierarchy of standard exceptions is shown below using an ASCII tree:</p>
<pre><code>exception
├── bad_alloc
│   └── bad_array_new_length
├── bad_cast
├── bad_exception
├── bad_typeid
├── logic_error
│   ├── domain_error
│   ├── future_error
│   ├── invalid_argument
│   ├── length_error
│   └── out_of_range
└── runtime_error
    ├── overflow_error
    ├── range_error
    ├── system_error
    │   └── ios_base::failure
    └── underflow_error</code></pre>
<ul>
<li><p>Typically, <code>logic_error</code>, <code>runtime_error</code> and their children are thrown in user code. These exceptions take a <code>std::string</code> or string literal as input.</p></li>
<li><p>You cannot throw <code>exception</code> or any of the language exceptions. You can however derive from the <code>exception</code> class to create your own exception.</p></li>
</ul>
<p><strong>Reference:</strong> §30.4.1.1 in The C++ Programming Language (4 Ed) by Stroustrup</p>
<hr />
<p><a href="rss.xml">RSS</a> - <a href="mailto:codeyarns@gmail.com">Contact</a></p>
</body>
</html>
