<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <meta name="author" content="Ashwin Nanjappa" />
  <title>Django core management error</title>
  <style type="text/css">code{white-space: pre;}</style>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143311697-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-143311697-1');
  </script>
</head>
<body>
<div id="header">
<h1 class="title">Django core management error</h1>
<h2 class="author">Ashwin Nanjappa</h2>
<h3 class="date">2016-01-13 12:20:19+00:00</h3>
</div>
<h1 id="problem">Problem</h1>
<p>I ran the <strong>Django</strong> <code>manage.py</code> script and got this error:</p>
<pre><code>ImportError: No module named django.core.management</code></pre>
<h1 id="solution">Solution</h1>
<p>The error message gives no indication of the true cause. This was required to be executed in a virtualenv and I had not <strong>activated</strong> the virtualenv, hence the error. It went away when I ran it after activating the virtualenv.</p>
<hr />
<p><a href="..">Code Yarns</a> / <a href="index.html">Tech Blog</a></p>
</body>
</html>
